[package]
name = "factory_pattern"
version = "1.0.0"
authors = ["Warren Hodgkinson <warren.hodgkinson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
